@if($tab === 'regions')
<div class="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">Status</label><select x-model="regionStatusFilter" class="w-full rounded-xl border-2 border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div>
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">Region Code</label><input type="text" x-model="regionCodeFilter" placeholder="Search code..." class="w-full rounded-xl border-2 border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 outline-none placeholder:text-slate-400 focus:border-orange-400 focus:ring-4 focus:ring-orange-100"></div>
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">Coverage</label><select x-model="regionCoverageFilter" class="w-full rounded-xl border-2 border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"><option value="">Any coverage</option><option value="has_districts">Has districts</option><option value="no_districts">No districts</option><option value="has_towns">Has towns</option><option value="no_towns">No towns</option><option value="has_active_towns">Has active towns</option><option value="no_active_towns">No active towns</option></select></div>
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">District Count</label><div class="grid grid-cols-2 overflow-hidden rounded-xl border-2 border-slate-200 bg-white focus-within:border-orange-400 focus-within:ring-4 focus-within:ring-orange-100"><input type="number" min="0" x-model="regionDistrictsMin" placeholder="Min" class="min-w-0 border-0 px-3 py-3 text-sm font-semibold text-slate-900 outline-none"><input type="number" min="0" x-model="regionDistrictsMax" placeholder="Max" class="min-w-0 border-0 border-l border-slate-200 px-3 py-3 text-sm font-semibold text-slate-900 outline-none"></div></div>
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">Town Count</label><div class="grid grid-cols-2 overflow-hidden rounded-xl border-2 border-slate-200 bg-white focus-within:border-orange-400 focus-within:ring-4 focus-within:ring-orange-100"><input type="number" min="0" x-model="regionTownsMin" placeholder="Min" class="min-w-0 border-0 px-3 py-3 text-sm font-semibold text-slate-900 outline-none"><input type="number" min="0" x-model="regionTownsMax" placeholder="Max" class="min-w-0 border-0 border-l border-slate-200 px-3 py-3 text-sm font-semibold text-slate-900 outline-none"></div></div>
</div>
<div class="mt-4 flex flex-wrap items-center justify-end gap-3 border-t border-slate-200 pt-4"><button type="button" @click="showRegionFilters = false" class="mr-auto rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 transition hover:bg-slate-50">Close Filters</button><button type="button" @click="clearRegionFilters()" class="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 transition hover:bg-slate-50">Clear Filters</button><button type="button" @click="applyRegionFilters()" class="rounded-xl bg-orange-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-orange-600/20 transition hover:bg-orange-700">Apply Filters</button></div>
@elseif($tab === 'districts')
<div class="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">Region</label><select x-model="districtRegionFilter" class="w-full rounded-xl border-2 border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"><option value="">All regions</option><template x-for="r in regions" :key="r.id"><option :value="r.id" x-text="r.name"></option></template></select></div>
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">Status</label><select x-model="districtStatusFilter" class="w-full rounded-xl border-2 border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div>
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">District Code</label><input type="text" x-model="districtCodeFilter" placeholder="Search code..." class="w-full rounded-xl border-2 border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 outline-none placeholder:text-slate-400 focus:border-orange-400 focus:ring-4 focus:ring-orange-100"></div>
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">Region Status</label><select x-model="districtRegionStatusFilter" class="w-full rounded-xl border-2 border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"><option value="">Any parent region</option><option value="active">Active region</option><option value="inactive">Inactive region</option></select></div>
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">Town Coverage</label><select x-model="districtCoverageFilter" class="w-full rounded-xl border-2 border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"><option value="">Any coverage</option><option value="has_towns">Has towns</option><option value="no_towns">No towns</option><option value="has_active_towns">Has active towns</option><option value="no_active_towns">No active towns</option></select></div>
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">Town Count</label><div class="grid grid-cols-2 overflow-hidden rounded-xl border-2 border-slate-200 bg-white focus-within:border-orange-400 focus-within:ring-4 focus-within:ring-orange-100"><input type="number" min="0" x-model="districtTownsMin" placeholder="Min" class="min-w-0 border-0 px-3 py-3 text-sm font-semibold text-slate-900 outline-none"><input type="number" min="0" x-model="districtTownsMax" placeholder="Max" class="min-w-0 border-0 border-l border-slate-200 px-3 py-3 text-sm font-semibold text-slate-900 outline-none"></div></div>
</div>
<div class="mt-4 flex flex-wrap items-center justify-end gap-3 border-t border-slate-200 pt-4"><button type="button" @click="showDistrictFilters = false" class="mr-auto rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 transition hover:bg-slate-50">Close Filters</button><button type="button" @click="clearDistrictFilters()" class="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 transition hover:bg-slate-50">Clear Filters</button><button type="button" @click="applyDistrictFilters()" class="rounded-xl bg-orange-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-orange-600/20 transition hover:bg-orange-700">Apply Filters</button></div>
@else
<div class="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">Region</label><select x-model="townRegionFilter" @change="townDistrictFilter = ''; loadTownDistricts()" class="w-full rounded-xl border-2 border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"><option value="">All regions</option><template x-for="r in regions" :key="r.id"><option :value="r.id" x-text="r.name"></option></template></select></div>
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">District</label><select x-model="townDistrictFilter" class="w-full rounded-xl border-2 border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"><option value="">All districts</option><template x-for="d in townFilterDistricts" :key="d.id"><option :value="d.id" x-text="d.name"></option></template></select></div>
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">Type</label><select x-model="townTypeFilter" class="w-full rounded-xl border-2 border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"><option value="">Any type</option><option value="city">City</option><option value="town">Town</option><option value="suburb">Suburb</option><option value="village">Village</option></select></div>
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">Status</label><select x-model="townStatusFilter" class="w-full rounded-xl border-2 border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div>
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">Region Status</label><select x-model="townRegionStatusFilter" class="w-full rounded-xl border-2 border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"><option value="">Any region</option><option value="active">Active region</option><option value="inactive">Inactive region</option></select></div>
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">District Status</label><select x-model="townDistrictStatusFilter" class="w-full rounded-xl border-2 border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"><option value="">Any district</option><option value="active">Active district</option><option value="inactive">Inactive district</option></select></div>
    <div><label class="mb-2 block text-xs font-extrabold uppercase tracking-wide text-slate-600">Route Health</label><select x-model="townParentStateFilter" class="w-full rounded-xl border-2 border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100"><option value="">Any route health</option><option value="ready">Active region + district</option><option value="inactive_region">Inactive region</option><option value="inactive_district">Inactive district</option></select></div>
</div>
<div class="mt-4 flex flex-wrap items-center justify-end gap-3 border-t border-slate-200 pt-4"><button type="button" @click="showTownFilters = false" class="mr-auto rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 transition hover:bg-slate-50">Close Filters</button><button type="button" @click="clearTownFilters()" class="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 transition hover:bg-slate-50">Clear Filters</button><button type="button" @click="applyTownFilters()" class="rounded-xl bg-orange-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-orange-600/20 transition hover:bg-orange-700">Apply Filters</button></div>
@endif
